2021-08-13 16:05:09,711 - __main__ -test - ERROR- error
Traceback (most recent call last):
  File "F:/Python38 Project/oneconnect/test.py", line 16, in <module>
    result = 10 / 0
ZeroDivisionError: division by zero
2021-08-13 16:05:09,711 - __main__ -test - INFO- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2021-08-13 16:05:56,518 - __main__ -test - ERROR- info
Traceback (most recent call last):
  File "F:/Python38 Project/oneconnect/test.py", line 16, in <module>
    result = 10 / 0
ZeroDivisionError: division by zero
2021-08-13 16:05:56,518 - __main__ -test - INFO- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2021-08-13 16:40:32,118 - __main__ -test - ERROR- 提示信息：
Traceback (most recent call last):
  File "F:/Python38 Project/oneconnect/test.py", line 16, in <module>
    result = 10 / 0
ZeroDivisionError: division by zero
2021-08-13 16:40:32,119 - __main__ -test - INFO- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
